version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./backend/dotenv/.env
    depends_on:
      - database

  database:
    image: postgres:16.0-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./backend/dotenv/.env
